spring:
  application:
    name: payment-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:payment_db
    username: ${DB_USER:sa}
    password: ${DB_SECRET:password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: ${FORMAT_SQL:false}
  h2:
    console.enabled: true
  kafka:
    bootstrap-servers: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port : 8085